name: CMake

on: [push, pull_request]

# Automatically cancel previous runs of this workflow on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    env:
      BUILD_TYPE: Release
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v5
    
    - name: Build
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DTEST_RELEASE=${{ startsWith(github.ref, 'refs/tags/') && 'ON' || 'OFF' }}
        cmake --build build --config ${{ env.BUILD_TYPE }} --parallel
        cmake --install build --prefix ./install --config ${{ env.BUILD_TYPE }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-${{ matrix.os }}
        path: install/bin/*

    - name: Get lowercase OS name
      id: osname
      uses: ASzc/change-string-case-action@v6
      with:
        string: ${{ runner.os }}

    - name: Compress artifacts
      uses: papeloto/action-zip@v1
      with:
        files: install/bin/
        dest: ${{ github.event.repository.name }}-${{ steps.osname.outputs.lowercase }}.zip

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ github.event.repository.name }}-${{ steps.osname.outputs.lowercase }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}